config/routes.rb
Rails.application.routes.draw do
  get 'sales/new'
  post 'sales', to: 'sales#create'
  get 'sales/done'
  root 'sales#done'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/sale.rb
class Sale < ApplicationRecord
  # El campo cod debe ser único (uniqueness)
  validates :cod, uniqueness: true
  # El detalle debe estar presente (presence)
  validates :detail, presence: true
  # La categoría debe estar contenida dentro de la siguiente colección: (inclusion)
  validates :category, inclusion: %w('uno' 'dos' 'tres' 'cuatro')
  # El campo value debe ser entero y positivo (numericality)
  validates :value, numericality: true
  # El campo discount debe ser entero, positivo y menor o igual a 40
  validates :discount, numericality: { only_integer: true, less_than_or_equal_to: 40 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/sales_controller.rb
class SalesController < ApplicationController
  def new
    @sale = Sale.new
  end

  def create
    @sale = Sale.new(sale_params)
    # Aplicando descuento al total:
    @sale.total = @sale.value - (@sale.value * @sale.discount / 100)

    # Aplicando Iva:
    if @sale.tax.zero?
      @sale.total =  @sale.total * 1.19
      @sale.tax = 19
    else
      @sale.tax = 0
    end

    # Respuesta:
    respond_to do |format|
      if @sale.save
        format.html { redirect_to sales_done_path, notice: 'El registro fue almacenado con éxito!' }
      else
        format.html { render :new }
      end
    end
  end

  def done
    @sales = Sale.all
  end

  private
  def sale_params
    params.require(:sale).permit(:cod, :detail, :category, :value, :discount, :tax, :total)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sales_helper.rb
module SalesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Actividad25</title>
    <%= csrf_meta_tags %>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% if alert.present? %>
      <div class="alert alert-danger" role="alert">
        <%= alert %>
      </div>
    <% end %>

    <% if notice.present? %>
      <div class="alert alert-success" role="alert">
        <%= notice %>
      </div>
    <% end %>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/sales/done.html.erb
<h3 class="text-info">Ventas:</h3>
<br>
<table class="table table-responsive-md">
  <thead class="thead-dark">
    <tr>
      <th scope="col">#</th>
      <th scope="col">Cod.</th>
      <th scope="col">Category</th>
      <th scope="col">Detail</th>
      <th scope="col">Value</th>
      <th scope="col">Discount</th>
      <th scope="col">Tax</th>
      <th scope="col">Total</th>
    </tr>
  </thead>

  <tbody>
    <% @sales.each do |sale| %>
    <tr>
      <td><%= sale.id %></td>
      <td><%= sale.cod %></td>
      <td><%= sale.category %></td>
      <td><%= sale.detail %></td>
      <td><%= sale.value %></td>
      <td><%= sale.discount %></td>
      <td><%= sale.tax %></td>
      <td><%= sale.total %></td>
    </tr>
    <% end %>
  </tbody>
</table>

<div class="d-flex justify-content-center">
  <%= link_to 'Ingresar venta', sales_new_path, class: 'btn btn-outline-success' %>
</div>

app/views/sales/new.html.erb
<div class="row d-flex justify-content-center my-3">
  <div class="col-sm-12 col-md-6 col-lg-6">
    <h3 class="text-info">Formulario</h3>
    <%= form_with model: @sale, local: true do |f| %>
      <div class="form-group">
        <%= f.label :cod, 'Código' %>
        <%= f.number_field :cod, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= f.label :detail, 'Detalle' %>
        <%= f.text_area :detail, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= f.label :category, 'Categoría' %>
        <%= f.number_field :category, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= f.label :value, 'Valor' %>
        <%= f.number_field :value, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= f.label :discount, 'Descuento' %>
        <%= f.number_field :discount, class: 'form-control' %>
      </div>

      <div class="form-group form-check">
        <%= f.check_box :tax, class: 'form-check-input' %>
        <%= f.label :tax, 'IVA', class: 'form-check-label' %>
      </div>

      <div class="d-flex justify-content-between">
        <%= f.submit 'Ingresar Venta', class: 'btn btn-outline-info' %>
        <%= link_to 'Ventas', root_path, class: 'btn btn-outline-success' %>
      </div>
    <% end %>
  </div>
</div>